apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dotnet-api
  namespace: dotnet-dev
spec:
  rules:
  - host: dotnetapi-dev.k8s.local
    http:
      paths:
      - backend:
          serviceName: dotnet-api
          servicePort: 80
