---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnetapi-dev
  namespace: argocd
spec:
  project: default 
  source: 
    repoURL: https://github.com/pkhamdee/dotnet-api-kpack.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.docker.internal:6443
    namespace: kpack-builders
  syncPolicy:
    automated:
      prune: true

