apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dotnet-api
  namespace: dotnet-dev
spec:
  rules:
  - host: dotnetapi-stage.tkg.pkhamdee.com
    http:
      paths:
      - backend:
          serviceName: dotnet-api
          servicePort: 80
