apiVersion: apps/v1 
kind: Deployment
metadata:
  name: dotnet-api
  namespace: dotnet-dev
  labels:
    app: dotnet-api
spec:
  selector:
    matchLabels:
      app: dotnet-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - image: pkhamdee/dotnet-api:latest
        name: dotnet-api
        securityContext:
          runAsUser: 0
