apiVersion: v1
kind: Service
metadata:
 name: dotnet-api
 namespace: dotnet-dev
spec:
 type: ClusterIP
 selector:
   app: dotnet-api
 ports:
   - name: client
     protocol: TCP
     port: 80
 selector:
   app: dotnet-api 
